# Circle configuration to preview the opencontainers/org site as artifact

version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: ~/repo
    environment:
      - JEKYLL_ENV: production
      - NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      - BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - checkout
      - restore_cache:
          keys:
          - rubygems-v1
      - run:
          name: Bundle Install
          command: |
              cd ~/repo/docs
              bundle check || bundle install
      - save_cache:
          key: rubygems-v1
          paths:
            - vendor/bundle
      - run:
          name: Jekyll Build
          command: |              
              echo "Building Container Magic!"
              mv ~/repo/.circleci/circle_urls.sh ~/repo/docs/circle_urls.sh
              cd ~/repo/docs
              chmod u+x circle_urls.sh
              bash circle_urls.sh              
              bundle exec jekyll build
      - store_artifacts:
          path: ~/repo/docs/_site
          destination: org

workflows:
  version: 2
  build-site:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
