# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OpenContainers
description: Open containers man pages
baseurl: "/org" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

repo: https://www.github.com/opencontainers/org

permalink: pretty
exclude: 
 - "*.gem"
 - _site
 - "Gemfile"
 - "Gemfile.lock"

# Aux links for the upper right navigation
aux_links:
  "OpenContainers on GitHub":
    - "//github.com/opencontainers"

footer_links:
  "Developer Meetings": https://github.com/opencontainers/org#meetings
  "Mailing List": https://groups.google.com/a/opencontainers.org/forum/#!forum/dev
  "Slack": https://chat.opencontainers.org/
  "GitHub": https://github.com/opencontainers
  "Issue Tracker": https://github.com/opencontainers/org/issues
